server:
  port: 8099


#logback日志配置
logging:
  level:
    root: info


springdoc:
  api-docs:
    enabled: true # 开启OpenApi接口
    path: /v3/api-docs  # 自定义路径，默认为 "/v3/api-docs"
  swagger-ui:
    enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
#    path: /test/swagger-ui/index.html # 自定义路径，默认为"/swagger-ui/index.html"


spring:
  profiles:
    active: dev
  application:
    name: testStudy
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #引入druid数据源
    url: jdbc:mysql://localhost:3306/rbac?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345

    druid:
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL

  #    redis相关配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 20  #连接池最大连接数（使用负值表示没有限制,默认8）
          min-idle: 0     #空闲连接
          max-idle: 8 # 连接最大空闲时间（毫秒），超时则关闭，默认8
          max-wait: -1  #最大等待时间，超时则报错，负值无限制，默认-1


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# mybatis　相关　ｘｍｌ文件在哪里　驼峰　　分页插件　打印ｓｑｌ语句的日志
mybatis:
  # 扫描映射文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰映射配置
    map-underscore-to-camel-case: true


#jwt相关配置
config:
  jwt:
    #    加密密钥
    secret: qwejisdjqwekg[pwejqwk[fdaaffgqweqwgyuolp[wekpvaqwe3q423dsf
    #    有效时长 单位秒
    expiration: 604800 # 7 days in seconds




